// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUVPpRrq10OgrBsjhKc99HKDAVpjbm_w',
    appId: '1:183967406660:web:58e3dc7d7ce27c16e1ba11',
    messagingSenderId: '183967406660',
    projectId: 'fitnesspal-87234',
    authDomain: 'fitnesspal-87234.firebaseapp.com',
    storageBucket: 'fitnesspal-87234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtqw-bUaDui8KJ1BFJroAhbvsQB-64Xo',
    appId: '1:183967406660:android:1d899652ff49a96ce1ba11',
    messagingSenderId: '183967406660',
    projectId: 'fitnesspal-87234',
    storageBucket: 'fitnesspal-87234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9U8YkO5GnwVXw9Bon0M2r6Cr5iOpo1Y',
    appId: '1:183967406660:ios:92e028d8ee1a8ebee1ba11',
    messagingSenderId: '183967406660',
    projectId: 'fitnesspal-87234',
    storageBucket: 'fitnesspal-87234.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
